name: Deploy a Azure
on:
  push:
    branches:
      - main  # Solo se dispara cuando envías código a la rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Login via Azure CLI'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_ACCESS }} # Asegúrate que este nombre coincida con tu Secret

      - name: 'Probar conexión'
        run: |
          az account show  # Esto imprime los detalles de tu suscripción si el login fue exitoso
          
      - name: 'Deploy to Azure'
        run: |
          # Aquí iría tu comando real de despliegue
          echo "Desplegando en Azure..."